spring:
  application:
    name: consulDemoPayment
  cloud:
    consul:
      discovery:
#        tags: dev
        # 服务发现过滤的tag
#        default-query-tag: dev
        instance-id: payment-1
        serviceName: ${spring.application.name}
        hostname: 10.11.73.10
#        heartbeat:
#          enabled: true

      #        include-hostname-in-instance-id: true
      #        health-check-url:
      host: localhost
      port: 8500
  profiles:
    active: dev