spring:
  application:
    name: consulDemoOrder
  cloud:
    consul:
      discovery:
        tags: dev
        # 服务发现过滤的tag
#        default-query-tag: dev
        instance-id: ${spring.application.name}
        serviceName: ${spring.application.name}
#        hostname: localhost
      #        health-check-url:
      host: localhost
      port: 8500
  profiles:
    active: dev